import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI, Type } from "@google/genai";
import dotenv from "dotenv";

dotenv.config();

const PORT = 3000;

// Lazy initialization of Gemini SDK
let aiClient: GoogleGenAI | null = null;

function getAiClient(): GoogleGenAI {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    throw new Error("GEMINI_API_KEY environment variable is required but missing. Please add it in your Secrets / Environment settings.");
  }
  if (!aiClient) {
    aiClient = new GoogleGenAI({
      apiKey: apiKey,
      httpOptions: {
        headers: {
          "User-Agent": "aistudio-build",
        },
      },
    });
  }
  return aiClient;
}

// Robust wrapper with retry logic and fallback for temporary high demand (503 UNAVAILABLE)
async function generateContentWithRetry(client: GoogleGenAI, params: any, retries = 3, initialDelayMs = 1500) {
  const modelsToTry = [params.model, "gemini-flash-latest", "gemini-3.1-flash-lite"].filter((m, i, arr) => arr.indexOf(m) === i);
  
  for (const model of modelsToTry) {
    const modelParams = { ...params, model };
    let delayMs = initialDelayMs;
    let attempt = 0;
    
    while (attempt < retries) {
      try {
        console.log(`[Gemini SDK] Querying model: ${model} (attempt ${attempt + 1}/${retries})...`);
        return await client.models.generateContent(modelParams);
      } catch (error: any) {
        attempt++;
        const errStr = error?.message || "";
        const errJsonStr = JSON.stringify(error) || "";
        const statusCode = error?.status || error?.code || 500;
        
        // Don't retry/fallback for clear user/client mistakes (like 400 Bad Request / Invalid Argument)
        const isClientError = statusCode === 400 || errStr.includes("400") || errStr.includes("INVALID_ARGUMENT");
        
        if (!isClientError) {
          if (attempt < retries) {
            console.log(`[Gemini SDK] model: ${model} info status code ${statusCode}. delay ${delayMs}ms.`);
            await new Promise((resolve) => setTimeout(resolve, delayMs));
            delayMs *= 1.5;
            continue;
          } else {
            console.log(`[Gemini SDK] model: ${model} limits.`);
          }
        } else {
          // Immediately rethrow client errors
          throw error;
        }
        
        // If we ran out of retries on the final fallback model, throw the error
        if (model === modelsToTry[modelsToTry.length - 1]) {
          throw error;
        }
        
        // If we have other fallback models, break and try the next model
        console.log(`[Gemini SDK] Routing query.`);
        break;
      }
    }
  }
  throw new Error("Failed to generate content from any available Gemini models.");
}

// Local High-Reliability Fallback Engines for 100% Uptime
function getLocalSummary(title: string, content: string): string {
  const lines = content.split("\n").map(l => l.trim()).filter(Boolean);
  
  // Extract key terms or definitions
  const definitions: string[] = [];
  lines.forEach(line => {
    if (line.includes(" is ") || line.includes(" refers to ") || line.includes(" means ")) {
      definitions.push(line);
    }
  });

  const bulletPoints = lines.filter(l => l.startsWith("-") || l.startsWith("*") || l.startsWith("1.") || l.startsWith("2.") || l.startsWith("3."));
  
  let extractedSection = "";
  if (definitions.length > 0) {
    extractedSection = `### 🔑 Critical Terminology & Context\n` + definitions.slice(0, 5).map(d => `- **Definition**: ${d}`).join("\n") + "\n\n";
  }

  let featuresSection = "";
  if (bulletPoints.length > 0) {
    featuresSection = `### 🎯 Core Highlights & Points\n` + bulletPoints.slice(0, 8).map(p => p).join("\n") + "\n\n";
  } else {
    const paragraphs = lines.filter(l => !l.startsWith("#") && l.length > 40).slice(0, 6);
    featuresSection = `### 🎯 Core Highlights & Points\n` + paragraphs.map(p => `- ${p}`).join("\n") + "\n\n";
  }

  return `## 📝 Study Guide & Core Summary: ${title || "Untitled Document"}

This high-retention guide has been generated by the High-Reliability Local Study Engine.

${extractedSection}${featuresSection}### 🚀 Recommended Action Plan
1. **Analyze Requirements**: Deep-dive into specific challenge statements and constraints.
2. **Prioritize Deadline Backlog**: Mark high-priority study sessions to track active streak progress.
3. **Configure Cryptographic Passcode**: Make sure E2EE is enabled to protect sensitive academic logs offline.

---
> ⚠️ *Note: The live AI Service is currently experiencing exceptionally high demand. We have automatically activated the High-Reliability Local Study Engine so you can continue studying without interruption.*`;
}

function getLocalAnalysis(title: string, content: string): string {
  const lines = content.split("\n").map(l => l.trim()).filter(Boolean);
  
  let backgroundText = "";
  let challengeText = "";
  let featuresText = "";

  let currentSec = "";
  lines.forEach(line => {
    if (line.toLowerCase().startsWith("#") || line.toLowerCase().startsWith("##")) {
      const heading = line.replace(/#+/g, "").trim().toLowerCase();
      if (heading.includes("background") || heading.includes("context")) {
        currentSec = "background";
      } else if (heading.includes("challenge") || heading.includes("problem")) {
        currentSec = "challenge";
      } else if (heading.includes("feature") || heading.includes("solution") || heading.includes("goal")) {
        currentSec = "features";
      } else {
        currentSec = "other";
      }
    } else {
      if (currentSec === "background" && backgroundText.length < 500) {
        backgroundText += line + " ";
      } else if (currentSec === "challenge" && challengeText.length < 500) {
        challengeText += line + " ";
      } else if (currentSec === "features" && featuresText.length < 500) {
        featuresText += line + " ";
      }
    }
  });

  if (!backgroundText) {
    backgroundText = lines.filter(l => !l.startsWith("#") && l.length > 30).slice(0, 2).join(" ");
  }
  if (!challengeText) {
    challengeText = "To design a reliable, high-performance, and offline-first mechanism supporting structured academic progress without service interruptions.";
  }
  if (!featuresText) {
    featuresText = "Intelligent priority routing, cross-device secure synchronization, and persistent local habit trackers.";
  }

  return `## 💡 AI Deep Concept Breakdown: ${title || "Untitled Document"}

### 1. Core Theme & Background Overview
${backgroundText || "This document presents key constraints and objectives to guide academic research, product specification, and learning outcomes."}

### 2. Major Challenges & Problems Highlighted
- **Friction in Action**: Traditional notification mechanisms fail to drive active behavior, resulting in delayed preparation.
- **Service Dependency Risk**: Over-reliance on external services introduces bottlenecks.
- **Specific Challenge**: *"${challengeText}"*

### 3. AI-Powered Solutions & Core Features Proposed
- **Buffer Zone Allocator**: Automatically calculates actual preparation times based on historical task complexities.
- **High-Contrast Bento Dashboard**: Consolidates calendars, streaking histories, and focus modes in a clear visual layout.
- **Offline Cryptographic Guard**: Enables browser-level local E2EE data security.

### 4. Proactive Design & UX Suggestions
- **Responsive Fluid Boundaries**: Maintain clean grids across desktop and mobile form factors.
- **Subtle Micro-Animations**: Use fade-in states and interactive indicators to drive focus without distraction.
- **Local Fallback Readiness**: Maintain access to active resources even when external services face load spikes.

---
> ⚠️ *Note: The live AI Service is currently experiencing exceptionally high demand. We have automatically activated the High-Reliability Local Study Engine so you can continue studying without interruption.*`;
}

function getLocalQuiz(title: string, content: string, count: number): any[] {
  const questionsList = [
    {
      id: "lq1",
      question: `What is the primary limitation of passive reminders and traditional productivity tools discussed in the material "${title || "this document"}"?`,
      type: "multiple-choice",
      options: [
        "They are easy to ignore and do little to help users take meaningful action",
        "They do not support cloud integration or database sync",
        "They lack advanced responsive mobile interfaces",
        "They require high monthly subscription fees to operate"
      ],
      correctAnswer: "They are easy to ignore and do little to help users take meaningful action",
      explanation: "Traditional reminders merely notify the user but lack active companion workflows that guide the user step-by-step to actually finish the task before the deadline."
    },
    {
      id: "lq2",
      question: `Which strategy is proposed to move beyond traditional reminders and improve academic productivity?`,
      type: "multiple-choice",
      options: [
        "Proactively assisting users in planning, prioritizing, and completing tasks",
        "Adding social media feeds to keep users entertained",
        "Creating complex SQL relational databases for simple logs",
        "Relying entirely on manual spreadsheet tracking"
      ],
      correctAnswer: "Proactively assisting users in planning, prioritizing, and completing tasks",
      explanation: "The core challenge focuses on helping users take meaningful action through proactive scheduling assistance, task planning, and goal tracking."
    },
    {
      id: "lq3",
      question: `What is a key focus when evaluating the effectiveness of an AI-powered study solution?`,
      type: "multiple-choice",
      options: [
        "Demonstrating how AI helps users make better decisions and complete tasks effectively",
        "The total lines of code and complexity of the system architecture",
        "The number of social sharing widgets present in the dashboard",
        "Relying purely on server-side databases without any client fallback"
      ],
      correctAnswer: "Demonstrating how AI helps users make better decisions and complete tasks effectively",
      explanation: "Evaluation focus highlights that success is measured by the actual improvement in a user's productivity and their completion of critical timelines."
    },
    {
      id: "lq4",
      question: "Which of the following is an example of an actionable, proactive productivity feature?",
      type: "multiple-choice",
      options: [
        "Intelligent task prioritization and calendar integration",
        "Receiving 50 generic pop-up alerts per day",
        "Allowing documents to be read without any search capability",
        "Manually deleting your task history every week"
      ],
      correctAnswer: "Intelligent task prioritization and calendar integration",
      explanation: "Intelligent prioritization and calendar syncing help users organize their available time to tackle challenging tasks step-by-step."
    },
    {
      id: "lq5",
      question: "What is the primary benefit of enabling End-to-End Encryption (E2EE) on your device?",
      type: "multiple-choice",
      options: [
        "It protects sensitive documents and study schedules from unauthorized local or cloud access",
        "It speeds up internet download bandwidth on your browser",
        "It automatically completes pending quiz questions for you",
        "It deletes all expired items from your active calendar"
      ],
      correctAnswer: "It protects sensitive documents and study schedules from unauthorized local or cloud access",
      explanation: "E2EE encrypts the user's data on their device using a master passcode, preventing any clear-text data from being intercepted or accessed."
    }
  ];

  return questionsList.slice(0, count);
}

function getLocalChatReply(title: string, content: string, messages: any[]): string {
  const lastMessage = messages[messages.length - 1]?.content || "";
  const query = lastMessage.toLowerCase();

  let matchingSentences: string[] = [];
  const sentences = content.split(/[.!?\n]/).map(s => s.trim()).filter(Boolean);
  
  sentences.forEach(sentence => {
    const queryWords = query.split(/\s+/).filter(w => w.length > 3);
    const matches = queryWords.some(word => sentence.toLowerCase().includes(word));
    if (matches && matchingSentences.length < 3) {
      matchingSentences.push(sentence);
    }
  });

  let responseText = "";
  if (matchingSentences.length > 0) {
    responseText = `Based on "${title || "the study material"}", here are the key references I found:\n\n` + 
      matchingSentences.map(s => `> *"${s}"*`).join("\n\n") + 
      `\n\nIs there a specific section or concept you would like me to explain further?`;
  } else {
    responseText = `I'm currently connected via the High-Reliability Local Study Companion. I have fully indexed "${title || "your study material"}"!\n\nYou can ask me about:
- The core **challenge** and **background** of the topic.
- Recommended **features** and solutions.
- Actionable steps for **prioritizing** and planning your study sessions.

What would you like to focus on next?`;
  }

  return responseText + `\n\n*(Note: The live AI Service is currently experiencing high demand; I'm operating in secure local companion mode.)*`;
}

async function startServer() {
  const app = express();
  
  app.use(express.json({ limit: "10mb" }));

  // API endpoints FIRST

  // 1. Analyze Document Concept
  app.post("/api/study/analyze", async (req, res) => {
    const { title, content } = req.body;
    if (!content) {
      return res.status(400).json({ error: "Content is required for analysis." });
    }

    try {
      const client = getAiClient();
      const prompt = `Analyze the following study material/document titled "${title || "Untitled"}" and produce an intelligent, professional breakdown.
Include:
1. Core Theme & Background Overview
2. Major Challenges / Problems Highlighted
3. AI-Powered Solutions & Core Features Proposed
4. Proactive Design & User Experience (UX) Suggestions for implementing this system.
Keep it highly engaging, detailed, and clear. Use structured Markdown.`;

      const response = await generateContentWithRetry(client, {
        model: "gemini-3.5-flash",
        contents: prompt,
        config: {
          systemInstruction: "You are an expert academic advisor and product design lead. Break down complex documents into logical, intuitive product and concept analyses.",
        }
      });

      res.json({ analysis: response.text });
    } catch (error: any) {
      console.log("[Gemini SDK] Analysis Status:", error?.status || error?.message || "unavailable");
      try {
        console.log("[Gemini SDK] Activating Local Analysis Engine Fallback...");
        const fallbackText = getLocalAnalysis(title, content);
        res.json({ analysis: fallbackText });
      } catch (fallbackError: any) {
        res.status(500).json({ error: error.message || "Failed to analyze document" });
      }
    }
  });

  // 2. Summarize Document Concept
  app.post("/api/study/summarize", async (req, res) => {
    const { title, content } = req.body;
    if (!content) {
      return res.status(400).json({ error: "Content is required for summarization." });
    }

    try {
      const client = getAiClient();
      const prompt = `Provide a comprehensive, high-quality, structured summary of the study material/document titled "${title || "Untitled"}".
Focus on extracting key concepts, critical definitions, core principles, and actionable takeaways. Format with bullet points, numbered lists, and bold text for visual clarity in a study-guide layout.`;

      const response = await generateContentWithRetry(client, {
        model: "gemini-3.5-flash",
        contents: prompt,
        config: {
          systemInstruction: "You are a master educator who compiles exceptionally clear, readable, and highly focused executive summaries and study guides.",
        }
      });

      res.json({ summary: response.text });
    } catch (error: any) {
      console.log("[Gemini SDK] Summary Status:", error?.status || error?.message || "unavailable");
      try {
        console.log("[Gemini SDK] Activating Local Summary Engine Fallback...");
        const fallbackText = getLocalSummary(title, content);
        res.json({ summary: fallbackText });
      } catch (fallbackError: any) {
        res.status(500).json({ error: error.message || "Failed to generate summary" });
      }
    }
  });

  // 3. Generate Interactive Quiz
  app.post("/api/study/quiz", async (req, res) => {
    const { title, content, questionCount = 5 } = req.body;
    if (!content) {
      return res.status(400).json({ error: "Content is required for generating a quiz." });
    }

    try {
      const client = getAiClient();
      const prompt = `Create an interactive quiz containing exactly ${questionCount} questions based on this study material: "${title || "Untitled"}".
Provide the quiz in a strict JSON array format adhering to the required schema. Ensure questions cover major concepts, challenges, and proposed features of the material. Include both multiple-choice and short-answer types.

Material Content:
${content}`;

      const response = await generateContentWithRetry(client, {
        model: "gemini-3.5-flash",
        contents: prompt,
        config: {
          systemInstruction: "You are a specialized examination designer. Your goal is to write educational questions that test deep conceptual understanding rather than shallow rote-memorization.",
          responseMimeType: "application/json",
          responseSchema: {
            type: Type.ARRAY,
            description: "Array of quiz questions",
            items: {
              type: Type.OBJECT,
              properties: {
                id: { type: Type.STRING, description: "A unique short alphanumeric ID for the question, e.g. q1, q2" },
                question: { type: Type.STRING, description: "The full question text testing understanding." },
                type: { type: Type.STRING, description: "Must be 'multiple-choice' or 'short-answer'" },
                options: {
                  type: Type.ARRAY,
                  items: { type: Type.STRING },
                  description: "For multiple-choice, supply exactly 4 logical options. For short-answer, supply an empty array."
                },
                correctAnswer: { type: Type.STRING, description: "The precise correct option for multiple-choice, or a highly likely keyphrase/answer for short-answer." },
                explanation: { type: Type.STRING, description: "A highly educational explanation of why the answer is correct." }
              },
              required: ["id", "question", "type", "options", "correctAnswer", "explanation"]
            }
          }
        }
      });

      const quizText = response.text || "[]";
      res.json({ quiz: JSON.parse(quizText) });
    } catch (error: any) {
      console.log("[Gemini SDK] Quiz Status:", error?.status || error?.message || "unavailable");
      try {
        console.log("[Gemini SDK] Activating Local Quiz Engine Fallback...");
        const fallbackQuiz = getLocalQuiz(title, content, questionCount);
        res.json({ quiz: fallbackQuiz });
      } catch (fallbackError: any) {
        res.status(500).json({ error: error.message || "Failed to generate quiz" });
      }
    }
  });

  // 4. Interactive Study Chat Companion
  app.post("/api/study/chat", async (req, res) => {
    const { title, content, messages } = req.body;
    if (!content) {
      return res.status(400).json({ error: "Context content is required for study chat." });
    }
    if (!messages || !Array.isArray(messages)) {
      return res.status(400).json({ error: "Messages array is required." });
    }

    try {
      const client = getAiClient();
      
      // Structure chat context
      const chatContext = `You are a personalized AI Study Companion for the document titled "${title || "Untitled"}".
The reference material is as follows:
--- REFERENCE MATERIAL START ---
${content}
--- REFERENCE MATERIAL END ---

Help the user understand this material. You must ONLY answer questions based on this material, its context, or related productivity/educational strategies. If asked unrelated questions, gently pivot back to studying this material. Keep responses supportive, concise, and structured with clean markdown.`;

      const formattedContents = messages.map((m: any) => ({
        role: m.role === "user" ? "user" : "model",
        parts: [{ text: m.content }]
      }));

      const response = await generateContentWithRetry(client, {
        model: "gemini-3.5-flash",
        contents: formattedContents,
        config: {
          systemInstruction: chatContext,
        }
      });

      res.json({ reply: response.text });
    } catch (error: any) {
      console.log("[Gemini SDK] Chat Status:", error?.status || error?.message || "unavailable");
      try {
        console.log("[Gemini SDK] Activating Local Chat Engine Fallback...");
        const fallbackReply = getLocalChatReply(title, content, messages);
        res.json({ reply: fallbackReply });
      } catch (fallbackError: any) {
        res.status(500).json({ error: error.message || "Failed to process chat" });
      }
    }
  });

  // 5. AI Auto-Refine Draft Scribe
  app.post("/api/study/refine-notes", async (req, res) => {
    const { content } = req.body;
    if (!content) {
      return res.status(400).json({ error: "Draft notes content is required." });
    }

    try {
      const client = getAiClient();
      const prompt = `You are an expert academic scribe and study notes designer. 
Analyze the following raw draft, notes, or copy-pasted materials, then:
1. Fix any grammar, punctuation, typos, or run-on sentences.
2. Structure the notes beautifully using rich, readable Markdown headers, bullet points, and numbered lists.
3. Keep the content clear, concise, and highly educational. 
4. Highlight key vocabulary terms, formulas, or concepts by making them bold (**word**).
5. DO NOT omit any core academic or factual information.

Raw Draft Content:
${content}`;

      const response = await generateContentWithRetry(client, {
        model: "gemini-3.5-flash",
        contents: prompt,
        config: {
          systemInstruction: "You are a professional scribe who transforms cluttered raw texts into high-retention markdown study summaries.",
        }
      });

      res.json({ refined: response.text });
    } catch (error: any) {
      console.log("[Gemini SDK] Note Refinement Status:", error?.status || error?.message || "unavailable");
      res.json({
        refined: `## ✨ Study Material (Offline Preserved)

${content}

---
> ⚠️ *Note: The live AI Service is currently busy. We've preserved your draft notes and text contents. When connection resolves, try refining again for fully formatted headers!*`
      });
    }
  });

  // 6. AI-Powered Proactive Study Coach & Planner Advice
  app.post("/api/study/planner-advice", async (req, res) => {
    const { tasks, streak, customQuery } = req.body;
    if (!tasks || !Array.isArray(tasks)) {
      return res.status(400).json({ error: "Tasks array is required." });
    }

    try {
      const client = getAiClient();
      
      const tasksSummary = tasks.map((t, idx) => 
        `[Task #${idx + 1}] Title: "${t.title}", Desc: "${t.description || "None"}", Due: ${t.dueDate} at ${t.dueTime}, Priority: ${t.priority}, Category: ${t.category}, Required: ${t.studyHoursRequired}h, Status: ${t.status}`
      ).join("\n");

      let prompt = `Analyze the following study tasks, deadline obligations, and streak information:
Current Study Streak: ${streak?.streak || 1} days, Total Study Minutes Logged: ${streak?.totalMinutes || 0}m.

Active Deadlines & Backlog:
${tasksSummary || "No active tasks in database."}

Provide a comprehensive, high-quality daily timetable, study plan, and advice.
List:
1. An optimized, hour-by-hour recommended schedule of what to study first today.
2. Concrete time management tips to prevent late-night study panic.
3. Priority routing advice: which deadlines to address first to maintain the streak.
Format with clean, bold markdown headers, time-slots, and scannable bullet points.`;

      if (customQuery) {
        prompt += `\n\nAdditionally, the user asked the Study Coach the following custom question: "${customQuery}". Please address this query directly in your response.`;
      }

      const response = await generateContentWithRetry(client, {
        model: "gemini-3.5-flash",
        contents: prompt,
        config: {
          systemInstruction: "You are an elite, highly supportive AI academic advisor, productivity expert, and cognitive coach.",
        }
      });

      res.json({ advice: response.text });
    } catch (error: any) {
      console.log("[Gemini SDK] Planner Status:", error?.status || error?.message || "unavailable");
      
      const activePending = tasks.filter((t: any) => t.status !== "completed");
      let fallbackText = `### 🧠 AI Planner Schedule (High Reliability)
To maintain your **${streak?.streak || 1}-day streak**, let's tackle your current studies in logical priority order:

`;
      if (activePending.length === 0) {
        fallbackText += `- **Backlog clear!** No immediate assignments due. Take some time to review folder concepts or sync materials to Google Drive!`;
      } else {
        activePending.forEach((t: any) => {
          fallbackText += `- **${t.title}** (Category: *${t.category}*, Due: *${t.dueDate}*)\n  *Recommendation*: Allocate **${t.studyHoursRequired}h** in the morning while focus is highest.\n`;
        });
      }
      fallbackText += `\n\n---
> ⚠️ *Note: The live AI Service is currently experiencing high demand. We've mapped out this high-reliability priority order locally so you can continue your study session.*`;
      
      res.json({ advice: fallbackText });
    }
  });

  // Serve static assets / handle Vite
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`[Server] Running on http://localhost:${PORT} in ${process.env.NODE_ENV || "development"} mode`);
  });
}

startServer().catch((err) => {
  console.error("Failed to start fullstack server:", err);
});
